title: 경희무교로한의원
email: seongki1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

avatar: /assets/img/logo122.png

baseurl: "" # the subpath of your site, e.g. /blog
url: https://seongki1.github.io

disqus: mgrdoc

twitter_username: seongki1
github_username:  seongki1

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

collections:
  clinics:
    output: true
    # permalink: /clinics/:path

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
